M2Link/Controllers/LoginController.cs
using M2Link.Context;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace M2Link.Models
{
    public class LoginController : Controller
    {
        // GET: Form
        public ActionResult Form()
        {
            return View();
        }

        // POST: Form
        [HttpPost]
        public ActionResult Form(LoginModel model)
        {
            using (M2LinkContext context = new M2LinkContext())
            {
                UserRepository repo = new UserRepository(context);
                if (!repo.checkUser(model.nickname, model.password))
                {
                    ModelState.AddModelError("password", "Veuillez entrer des identifiants valides.");
                }
                if (!ModelState.IsValid)
                {
                    return View(model);
                }
                else
                {
                    FormsAuthentication.SetAuthCookie(model.nickname, true);
                    return RedirectToAction("Index", "Home");
                }
            }
        }

        [HttpGet]
        public ActionResult Disconnect()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Index", "Home");
        }
    }
}

M2Link/Controllers/RegisterController.cs
using M2Link.Context;
using M2Link.Entities;
using M2Link.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace M2Link.Controllers
{
    public class RegisterController : Controller
    {
        const string Password_Pattern = "^(?=.*[a-z])(?=.*[A-Z])(?=.*/d)(?=.*[@$!%*?&])[A-Za-z/d@$!%*?&]{8,}$";

        // GET: Form
        public ActionResult Form() => View();

        // POST : Form
        [HttpPost]
        public ActionResult Form(RegisterModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            else
            {
                User user = new User()
                {
                    first_name = model.first_name,
                    last_name = model.last_name,
                    email = model.email,
                    nickname = model.nickname,
                    password = model.password
                };

                using (M2LinkContext context = new M2LinkContext())
                {
                    UserRepository repo = new UserRepository(context);
                    repo.Add(user);
                    context.SaveChanges();
                }
                FormsAuthentication.SetAuthCookie(model.nickname, true);
                return RedirectToAction("Index", "Home");
            }
        }
    }
}

M2Link/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Projet .NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Projet .NET", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li>@Html.ActionLink("Accueil", "Index", "Home")</li>
                            <li>@Html.ActionLink("Profil", "Index", "Profile")</li>
                            <li>@Html.ActionLink("Déconnexion", "Disconnect", "Login")</li>
                            <li>@Html.ActionLink("?", "About", "Home", null, new { @class = "btn btn-sm btn-default btn-round" })</li>
                        }
                        else
                        {
                            <li>@Html.ActionLink("Connexion", "Form", "Login")</li>
                            <li>@Html.ActionLink("Inscription", "Form", "Register")</li>
                        }
                    </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - HAZARD Alexandre (@Html.ActionLink("Contact", "Contact", "Home"))</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>