M2Link/Entities/Message.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace M2Link.Entities
{
    public class Message
    {
        [KeyAttribute]
        public virtual Guid guid { get; set; }

        public User author { get; set; }

        public string message { get; set; }

        public DateTime date { get; set; }

        public Message()
        {
            this.guid = Guid.NewGuid();
            this.date = DateTime.Now;
        }

        public Message(User author, string message)
        {
            this.guid = Guid.NewGuid();
            this.author = author;
            this.message = message;
            this.date = DateTime.Now;
        }
    }
}

M2Link/Controllers/MessageController.cs
using M2Link.Context;
using M2Link.Entities;
using M2Link.Models;
using M2Link.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace M2Link.Controllers
{
    public class MessageController : Controller
    {
        // GET: Send
        public ActionResult Send()
        {
            return View();
        }

        // POST: Send
        [HttpPost]
        public ActionResult Send(MessageModel model)
        {
            using (M2LinkContext context = new M2LinkContext())
            {
                UserRepository userRepo = new UserRepository(context);
                User user = userRepo.getUser(HttpContext.User.Identity.Name);
                Message msg = new Message()
                {
                    author = user,
                    date = DateTime.Now,
                    guid = Guid.NewGuid(),
                    message = model.message
                };

                MessageRepository msgRepo = new MessageRepository(context);
                msgRepo.Add(msg);
                user.messages.Add(msg);

                context.SaveChanges();
            }
            return RedirectToAction("Index", "Home");
        }

        //GET : Delete
        public ActionResult Delete(MessageModel model)
        {
            using (M2LinkContext context = new M2LinkContext())
            {
                MessageRepository msgRepo = new MessageRepository(context);
                Message message = msgRepo.Get(model.guid);
                if (message == null)
                {
                    return RedirectToAction("Index","Profile");
                }
                else
                {
                    return View(model);
                }
            }
        }

        //POST : Delete
        [HttpPost]
        public ActionResult DeletePost(MessageModel model)
        {
            using (M2LinkContext context = new M2LinkContext())
            {
                MessageRepository msgRepo = new MessageRepository(context);
                msgRepo.Delete(model.guid);

                context.SaveChanges();
            }
            return RedirectToAction("Index", "Profile");
        }
    }
}

M2Link/Views/Message/Delete.cshtml
@model M2Link.Models.MessageModel

@{
    ViewBag.Title = "Suppression d'un message";
}
<h2>Suppression d'un message</h2>

<h3>Etes vous sûr de vouloir supprimer ce message ?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.guid)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.guid)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.message)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.message)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.author)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.author)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.date)
        </dd>

        <dt></dt>
        <dd>
            @using (Html.BeginForm("DeletePost", "Message"))
            {
                @Html.AntiForgeryToken()
                @Html.HiddenFor(model => model.guid)
                @Html.HiddenFor(model => model.message)
                @Html.HiddenFor(model => model.author)
                @Html.HiddenFor(model => model.date)

                <div class="form-actions no-color">
                    <input type="submit" value="Supprimer" class="btn btn-danger" />
                </div>
            }
        </dd>
    </dl>
</div>
@Html.ActionLink("Retour", "Index", "Profile", null, new { @class = "btn btn-sm btn-default" }) 

M2Link/Views/Message/Send.cshtml
@model M2Link.Models.MessageModel

@{
    ViewBag.Title = "Send";
}

<h2>Envoyer un message</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.message, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.message, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.message, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Envoyer" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Retour", "Index", "Home", null, new { @class = "btn btn-sm btn-default" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}